### PR TITLE
small fix in dma init

### PR DESCRIPTION
**Pull request by ali-rostami**
MemDataAlignment should be inited with DMA_MDATAALIGN_HALFWORD.

### CODE REVIEW

**Comment by ali-rostami** [comment]
AFAIK  it should be fixed in other examples too.

**Comment by embeddedt** [comment]
Looks valid; I wonder why this hasn't caused any issues thus far.

**Review by embeddedt — APPROVED** [review]

**Comment by embeddedt** [comment]
Confirmed that this change doesn't break anything on F746G-DISCO.

@kisvegabor We might need to apply this change to the F4-based boards and/or the F769 discovery board. I don't have either of those boards so I can't test this there; can you test and apply this change?

**Comment by kisvegabor** [comment]
I'll test it tomorrow on F429 and F769.

**Comment by kisvegabor** [comment]
Sorry for being late. 
I've just realized that the F769 doesn't use DMA because it caused artifacts.
Using `DMA_MDATAALIGN_HALFWORD` works well with F429 and I've updated the project.

I also wonder how was it working because these defines have different values.
image

image

**Comment by ali-rostami** [comment]
Yeah, It's intresting they were working.
Anyway thanks

**Pull request merged**
